organization_name: Save Democracy Indivisible North Inland
short_name: SDI-NI
tagline: Democracy, rule of law, civil rights, peaceful civic action
email: info@sdini.org
facebook: ""
instagram: ""
bluesky: ""
